name: Check
on: push

jobs:
  lint:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - name: Prepare & install
        run: |
          rm -rf node_modules package-lock.json
          npm ci                      # ci лучше install, если lock-файл есть/должен быть

      - name: Lint
        run: npm run lint

  test:
    needs: [lint]
    runs-on: [self-hosted, Linux, X64]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - name: Debug (для проверки)
        run: |
          echo "PATH: $PATH"
          which node || echo "node not found"
          which npm  || echo "npm not found"
          node -v
          npm -v

      - name: Prepare & install
        run: |
          rm -rf node_modules package-lock.json
          npm ci

      - name: Test
        run: npm run test
