name: Check
on: push

jobs:
  lint:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare Node Modules
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Lint
        run: npm run lint

  test:
    needs: [lint]
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare Node Modules
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Test
        run: npm run test
