name: CI/CD
on:
  push:
    branches:
      - dev
      - master

jobs:
  lint:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install
        run: npm ci
      - name: Lint
        run: npm run lint

  test:
    needs: lint
    runs-on: [self-hosted, Linux, X64]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install
        run: npm ci
      - name: Test
        run: npm run test

  deploy:
    needs: test
    runs-on: [self-hosted, Linux, X64]
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy
        run: |
          sudo rm -rf /var/www/dist_old
          sudo mv /var/www/dist /var/www/dist_old || true
          sudo mv dist /var/www/dist
